### ISSUE TITLE
Bucket URL does not always contain S3

### ISSUE THREAD

**Issue by Nr18** [seporaitis/yum-s3-iam#17]
On line 210 of the s3iam.py file you state:

TODO: bucket name finding is ugly, I should find a way to support
both naming conventions: http://bucket.s3.amazonaws.com/ and
http://s3.amazonaws.com/bucket/

This is true but what i always do is create a bucket called: mybucket.example.com and then the url is: mybucket.example.com.s3.amazonaws.com or s3.amazonaws.com/mybucket.example.com/ 

But if you create a CNAME like this:
mybucket.example.com. 300 IN CNAME mybucket.example.com.s3-eu-west-1.amazonaws.com.

You are able to address your content in your bucket like this: http://mybucket.example.com/repodata/....

So it would be great of you build support in for that usage as well.

**Comment by mbrossard** [comment]
I think this would be covered in #30, with a syntax like `s3://mybucket.example.com/`

If the bucket name has dots in them we have to use path-style URL instead of virtual-hosted–style URL (see [here](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro) for the differences), otherwise we'll get TLS validation errors. There's [a more detailed explanation on the topic](http://shlomoswidler.com/2009/08/amazon-s3-gotcha-using-virtual-host.html).

In any case we wouldn't be using the CNAME entry, because it would cause TLS issues (connecting to mybucket.example.com and getting a *.s3-eu-west-1.amazonaws.com certificate).
