### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by asedge** [seporaitis/yum-s3-iam#38]
No code has been pushed in about a year and there are pending PRs with no responses/feedback on them.

**Comment by seporaitis** [comment]
Hi, sorry about the pile of unanswered PRs - my inbox is terribly messy. I'd say the answer to your question unfortunately is yes. This plugin came out of necessity at work & over time we moved from CentOS to Ubuntu and from this OS package repository based deployment to something else (immutable machines).

If you or anyone who reads this is interested in taking the project over - let me know. One requirement would probably be to have a production environment which needs this project, otherwise after a brief cleanup of PRs it will flop back to the same sad state it is in now. But before anyone claims it - please read below:

I apologize if the following sounds cynical, but based on experience at my company - OS package based deployments do not scale well. Repo manifests and package/file listings are XML files. In our case we had a CI machine set up to build package on every new change in the repo - as the team grew, packages grew and repository grew and manifests grew as well. To the point where it took orders of magnitude longer to download and parse those XMLs than actually download and install latest package and launch the software. Most often the latest package is the one requested anyways, so one might end up just stripping the repository manifests to N recent packages, but in that case - why just not download files directly and do `rpm --install`? In which case package repository and this plugin - are not necessary. An S3 bucket and CloudFormation script is needed or some `Fabric` scripts to upload and install. But... there's more.

After `rpm --install` it is not guaranteed the software will work. It is on a different machine, for what it's worth, than on which unit & acceptance testing was done. Especially if there is a need to deploy an older version of the code. Granted, it doesn't happen often, but it does happen. If everything's on AWS - one would need to track AMIs linked to software versions. But if software is being built on an AWS Instance in the first place, and acceptance tests run on it & it is verified - why discard the instance and not make an AMI, which boots to a guaranteed working state with all OS dependencies?

So we ended up with immutable machines (AMIs) and so far it worked out great and this plugin and all PRs got lost in my messy Inbox.

Everyone has different production environments, of course, so above may not make sense or maybe you solved those issues differently, in that case - contact me if you want to take this project. It would be nice to be mentioned as original contributor or some such, but more importantly - I would love to know it is taken care of and used in production.

**Comment by asedge** [comment]
@seporaitis Thanks for taking the time to reply and share some of your experience!  Let's give it some time and see if anyone else weighs in on wanting to take over maintenance.  Not saying I won't do it but I want to give others who may have more time/desire a chance to speak up.

**Comment by revmischa** [comment]
Happy to do it if no one else wants to. I patched this too, but someone did it better I guess.

**Comment by mbrossard** [comment]
@seporaitis: I agree that if your instances are immutable and or ephemeral, OS packages might be adding more cost than value. In the case of long-running instance that must be updated, they still make sense. As you said different environments...

I need this code to keep running at work, so I'm already committed to fixing all problems I encounter on Amazon Linux and RHEL 6. The issues and pull requests show that there's an interest in keeping this project working, and I'm willing to take on this project.

**Comment by dbailey** [comment]
@seporaitis Thanks for the update, I'm interested in getting to the point where we just deploy AMIs, but we're not there yet. So until then I hope you'll pass the reins onto one of the volunteers in this thread.

**Comment by seporaitis** [comment]
Hi everyone, thanks for the interest! I have never transferred a project before. I see three potential candidates, but don't know how to approach this so the project continues and everyone is happy. Any suggestions?

**Comment by asedge** [comment]
I was thinking that we could create a new group in Github. I was going to do that but yesterday but couldn't think of a good name. Then we add the volunteers and @seporaitis so the project can be transferred directly.  Thoughts?

**Comment by revmischa** [comment]
Yeah either make a group or add everyone as collaborators

**Comment by seporaitis** [comment]
Sounds like a good plan! I don't know how to make a group, but I'll add you as collaborators.

**Comment by seporaitis** [comment]
Ok, added @asedge, @revmischa and @mbrossard as collaborators. @dbailey, you are interested in revival of the project, let me know if you want to be a collaborator.

Let me know if I can help you with anything else!

**Comment by mbrossard** [comment]
Thank you

**Comment by mbrossard** [comment]
I took it upon me to merge a fix for the bug affecting newer python 2.7 (there was already 4 pull requests).

**Comment by asedge** [comment]
@seporaitis Thanks.  To answer the original question, "No, this project is not dead."
