### ISSUE TITLE
s3iam.py fails when running outside of EC2

### ISSUE THREAD

**Issue by seren** [seporaitis/yum-s3-iam#48]
We are running yum inside of docker images which are run in EC2 for production and staging, and on developer's machines during dev and testing. Because of this, s3iam.py is trying to access S3 repos from either:
- EC2 (via IAM roles), or
- whitelisted IP addresses (via the S3 bucket policy)

Accessing from EC2 obviously works, but running yum from a whitelisted IP (eg. VPN, office, etc) fails with the error: `<urlopen error [Errno 111] Connection refused>`.

For this use-case, we should only try to retrieve IAM credentials if IAM is accessible, and fall back to normal un-authenticated access if not.

I'll submit the fix we implemented as a PR shortly.

**Comment by mbrossard** [comment]
Hi,

As mentioned in #49, I added the option to skip IAM authentication with an environment variable.

I've thought about the use-case you presented (building Docker images outside of EC2), and I'm not too fond of IP white-listing. When I encountered the same issue, I've worked around it by passing AWS API keys (use ARG not ENV, because ENV values are persisted in image, which is not what you want to do with API keys).

This was probably a little more complicated than necessary (involving some scripting), so I added in [50182a5] a fallback from IAM role to environment variable passed AWS API keys. You should be able to add to your `Dockerfile` the following lines:

```
ARG AWS_ACCESS_KEY_ID=""
ARG AWS_SECRET_ACCESS_KEY=""
```

Add `--build-arg AWS_ACCESS_KEY_ID=xxxx --build-arg AWS_SECRET_ACCESS_KEY=yyyy` to  to your `docker build` command-line


Sincerely,
Mathias

**Comment by mbrossard** [comment]
I'm preparing a 1.2.0 with those changes
