### ISSUE TITLE
http[s]://s3.amazonaws.com/<bucket> URLs don't work

### ISSUE THREAD

**Issue by mestudd** [seporaitis/yum-s3-iam#55]
I have URLs for repositories using https://s3.amazonaws.com/<bucket> prefixes. These do not work on my EC2 instances. I get an error:
<urlopen error [Errno -2] Name or service not known>

**Comment by mestudd** [comment]
Created pull request #56 to fix.

**Comment by mbrossard** [comment]
Hi,

Sorry about the delay. I misunderstood the issue because of #56. I don't think the problem is really the region detection (even though you can work-around the issue with your changes) but the URL we choose to use based on the region. The region is need to use v4 signatures.

If you can confirm that it is working for you, I'll make a new release.

Sincerely,
Mathias

**Comment by mestudd** [comment]
I can confirm that it is working for me.

Thanks.

**Comment by mbrossard** [comment]
Thank you for your help

**Comment by mbrossard** [comment]
Preparing 1.2.0 release
